### ISSUE TITLE
Can't call steam_api.dll

### ISSUE THREAD

**Issue by Bumbadawg** [PredatH0r/extraQL#2]
Hi,

running on Win10 pro x64 here.

extraQL launches the game, detects the game on close,
but apart from that no /steamnick nor r_autoFullscreen detected.
tried running as admin > 0.

Good luck ;-)

**Comment by PredatH0r** [comment]
Version 2.3 now has an option to install the .js script to your <steam-id>/baseq3/js folder instead of the workshop. It's a blind guess, but maybe your QL doesn't find the workshop folder.
When you start QL the scripts should be started too. They now print a green information line to the QL console. Can you take a look if you can see it?

Also, did you ever use extraQL 1.x or hook.js in the previous version of Quake Live?
A small percentage of users reportet that Quake Live wasn't executing hook.js (for unknown reasons) and it is very possible, that the new Quake Live has the same issue.

**Comment by Bumbadawg** [comment]
Ok so the 2.3 creates the dir and copy the .js.
[NOPE]Also btw: without the scripts it says in green the scripts were loaded (kind of a false positive here).[NOPE]
edit: extraQL is well loaded from the workshop folder so no false positive.

The names written in the form won't work on launch.
When typing the /steamnick ingame it display nothing, changes nothing but in the log it says :
http://127.0.0.1:27963/steamnick?name=^1TEST
So i think the process grabber can't access the steam profile API.

PS: I used extraQL 1.x in previous Quake Live but i removed them since.

**Comment by PredatH0r** [comment]
Thanks for the update.
When you get the green lines, it means that the scripts were loaded (the message is printed from inside the script), so that is good news.
It's also good that you see the URL in the log, which means the script iteself works.
As you suggested, it must be some issue with calling the steam_api.dll.

Inside the extraQL folder there should be a steam_api.dll and a steam_appid.txt file.
At this point in can think of 2 possible causes:
- somehow Steam thinks you are not allowed to run the application with the steam ID inside the steam_appid.txt file. Please try and edit the number to e.g. 1007. 
  (This will show up in your Steam match history as "Steamworks SDK Redist")
- an over-eager Anti-Virus tool may prevent extraQL.exe from loading the DLL (pure speculation, my Kaspersky AV doesn't block it)

**Comment by Bumbadawg** [comment]
> Thanks for the update.

Thanks for that cool tool :-)

In game, when i'm offline, it says it can't call steam_api.dll.
When i log in after some time /steamnick doesn't display that error but the name won't change.

For steam app id: i changed to 1007 but nothing special happens.
It automatically resets to the steam_appid.txt to 349090 (dedicated server appid) when launched.
By the way, Quake appid is 282440 (at least in France).

> This will show up in your Steam match history as "Steamworks SDK Redist"

I don't see what you mean. When right clicking on steam in taskbar and seeing recent games launched ?
I tried with other games id's but same thing.

##### Glitches :
- ticking case in settings for .js in extraQL launcher doesn't save.
- gameendcfg and not gameend.cfg is created in the baseq3 folder?

I will delve into your code to try to help (if it's in my reach)
maybe pull request

GL ;-)

**Comment by Bumbadawg** [comment]
the steam nick command in action with no effect

![untitled](https://cloud.githubusercontent.com/assets/1251056/10842469/1b8043f0-7ef2-11e5-8abd-a1f09cd47887.png)

**Comment by PredatH0r** [comment]
Technically, "/steamnick" is a cvar and extraQL gets a notification when it's value changes and then  calls the steam_api.dll. When you set the same value twice, QL will not send out a "change" notification and nothing happens. I'll add some code to reset the /steamnick in case of failure to prevent this.

Sorry for the AppID suggestion, I only realized now that extraQL always overwrites the file when you click the "Start" button. I'm using the Dedicated Server ID on purpose, because otherwise, after I load the DLL, Steam thinks that QL is already/still running and prevents the launch of the "real" QL.
I'll also add some code to allow testing different AppIDs to see if that helps. I'll also try another approach of loading the DLL. 

/r_autoFullscreen may not be set initially. In that case, please use /set r_autoFullscreen 3
I'll make sure to create the cvar in the next version.

Please stay tuned :)

**Comment by Bumbadawg** [comment]
Alright.
About the steam appid conflict between the dedicated server and the client, it's regular.
I had it with Killing Floor DS & client too.

**Comment by PredatH0r** [comment]
One more question: Are you running your Steam Client and extraQL as different windows users? Maybe one as Administrator and the other not?
extraQL+steam_api.dll can only communicate with the Steam Client when they run as the same user.

Can you try the beta version I prepared? https://github.com/PredatH0r/extraQL/releases/tag/v2.4beta1
Please open the Log, it will show if there are any exceptions loading steam_api.dll
You can also open the extraQL.ini file and add/change steamAppId=349090 to a different number (e.g. 1007).

**Comment by PredatH0r** [comment]
Next extraQL version will show a hint in the Log window to make sure to run both as the same user
